let elImg1 = document.querySelector('.image1')
let elImg2 = document.querySelector('.image2')
let elImg3 = document.querySelector('.image3')
let elImg4 = document.querySelector('.image4')
let elImg5 = document.querySelector('.image5')

elImg1.addEventListener('click', function(evt){
    elImg1.classList.add('image1')
    elImg1.classList.remove('image1__close')
    elImg2.classList.add('image2')
    elImg2.classList.remove('image2__open')
    elImg3.classList.add('image3')
    elImg3.classList.remove('image3__open')
    elImg4.classList.add('image4')
    elImg4.classList.remove('image4__open')
    elImg5.classList.add('image5')
    elImg5.classList.remove('image5__open')
})

elImg2.addEventListener('click', function(evt){
    elImg1.classList.remove('image1')
    elImg1.classList.add('image1__close')
    elImg2.classList.remove('image2')
    elImg2.classList.add('image2__open')
    elImg3.classList.add('image3')
    elImg3.classList.remove('image3__open')
    elImg4.classList.add('image4')
    elImg4.classList.remove('image4__open')
    elImg5.classList.add('image5')
    elImg5.classList.remove('image5__open')
})

elImg3.addEventListener('click', function(evt){
    elImg1.classList.remove('image1')
    elImg1.classList.add('image1__close')
    elImg2.classList.add('image2')
    elImg2.classList.remove('image2__open')
    elImg3.classList.remove('image3')
    elImg3.classList.add('image3__open')
    elImg4.classList.add('image4')
    elImg4.classList.remove('image4__open')
    elImg5.classList.add('image5')
    elImg5.classList.remove('image5__open')
})

elImg4.addEventListener('click', function(evt){
    elImg1.classList.remove('image1')
    elImg1.classList.add('image1__close')
    elImg2.classList.add('image2')
    elImg2.classList.remove('image2__open')
    elImg3.classList.add('image3')
    elImg3.classList.remove('image3__open')
    elImg4.classList.remove('image4')
    elImg4.classList.add('image4__open')
    elImg5.classList.add('image5')
    elImg5.classList.remove('image5__open')
})

elImg5.addEventListener('click', function(evt){
    elImg1.classList.remove('image1')
    elImg1.classList.add('image1__close')
    elImg2.classList.add('image2')
    elImg2.classList.remove('image2__open')
    elImg3.classList.add('image3')
    elImg3.classList.remove('image3__open')
    elImg4.classList.add('image4')
    elImg4.classList.remove('image4__open')
    elImg5.classList.remove('image5')
    elImg5.classList.add('image5__open')
})